//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public int ShipmentID { get; set; }
        public int OrderID { get; set; }
        public int RouteID { get; set; }
        public System.DateTime ShipmentDate { get; set; }
        public string ShipmentStatus { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Route Route { get; set; }
    }
}
